apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mtc
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /exports/PROD
    server: 10.245.95.175 
  persistentVolumeReclaimPolicy: Retain
