kind: Service
apiVersion: v1
metadata:
  name: http-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "mtcselect"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "60"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health.json"
spec:
  type: LoadBalancer
  selector:
    app: mtc
    tier: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
